USE slipperscorp;

ALTER TABLE authority
ADD FOREIGN KEY (functionality_id) REFERENCES functionality(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE role
ADD FOREIGN KEY (tenant_id) REFERENCES organization(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE roleauthoritymapping
ADD FOREIGN KEY (tenant_id) REFERENCES organization(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (authority_id) REFERENCES authority(id) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE user
ADD FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (tenant_id) REFERENCES organization(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE state
ADD FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE address
ADD FOREIGN KEY (tenant_id) REFERENCES organization(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (state_id) REFERENCES state(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (country_id) REFERENCES country(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE organization
ADD FOREIGN KEY (address_id) REFERENCES address(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE employee
ADD FOREIGN KEY (tenant_id) REFERENCES organization(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (communication_address_id) REFERENCES address(id) ON DELETE CASCADE ON UPDATE CASCADE,
ADD FOREIGN KEY (permanent_address_id) REFERENCES address(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- ALTER TABLE authority
-- ADD FOREIGN KEY (functionality_id) REFERENCES functionality(id) ON DELETE CASCADE ON UPDATE CASCADE,
-- ADD FOREIGN KEY (SchoolAcademicYearId) REFERENCES schoolacademicyear(Id) ON DELETE CASCADE ON UPDATE CASCADE,
-- ADD FOREIGN KEY (storedobjectid) REFERENCES storedobject(id) ON DELETE CASCADE ON UPDATE CASCADE;